// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// nearPPSD
List nearPPSD(mat X, const float eigenTol, const float convTol, const float psdTol, const int maxit);
RcppExport SEXP _nearPPSD_nearPPSD(SEXP XSEXP, SEXP eigenTolSEXP, SEXP convTolSEXP, SEXP psdTolSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const float >::type eigenTol(eigenTolSEXP);
    Rcpp::traits::input_parameter< const float >::type convTol(convTolSEXP);
    Rcpp::traits::input_parameter< const float >::type psdTol(psdTolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(nearPPSD(X, eigenTol, convTol, psdTol, maxit));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nearPPSD_nearPPSD", (DL_FUNC) &_nearPPSD_nearPPSD, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_nearPPSD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
