# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Finding the nearest patterned positive-semidefinite matrix
#'
#' @param X a numeric matrix.
#' @param eigenTol defines relative positiveness of eigenvalues compared to largest one.
#' @param convTol convergence tolerance.
#' @param psdTol tolerance for enforcing positive definiteness.
#' @param maxit maximum number of iterations allowed.
#'
#' @return A list of five elements.
#' 
#' \item{X}{The resulting patterned positive-semidefinite matrix.}
#' \item{iteration}{Number of iterations used.}
#' \item{convergence}{Whether the algorithmed converged.}
#' \item{normF}{Frobenius norm between the resulting optimal and the initial matrices.}
#' \item{normC}{Inf norm between the resulting optimal and the initial matrices.}
#' @author Julius Vainora
#' @references R. Escalante and M. Raydan \emph{Dykstra's Algorithm for a Constrained Least-squares Matrix Problem} Numerical Linear Algebra with Applications (1996) 459--471
#' @references H. Hu and I. Olkin \emph{A numerical procedure for finding the positive definite matrix closest to a patterned matrix} Statistics & Probability Letters (1991) 511--515
#' @references N. Higham \emph{Computing the nearest correlation matrix - a problem from finance} IMA Journal of Numerical Analysis (2002) 329--343
#' @export
nearPPSD <- function(X, eigenTol = 1e-06, convTol = 1e-07, psdTol = 1e-08, maxit = 100L) {
    .Call(`_nearPPSD_nearPPSD`, X, eigenTol, convTol, psdTol, maxit)
}

